### ISSUE TITLE
Trying to run the easy installation on OSX yields an error

### ISSUE THREAD

**Issue by wgottschalk** [Originate/exosphere#246]
I tried to run the following command as per the docs:
`curl https://raw.githubusercontent.com/Originate/exosphere-sdk/master/bin/install_osx | sh`
and got the following error:
`sh: line 1: 404:: command not found`

the manual installation works just fine

**Comment by kevgo** [comment]
Thanks for the bug report! The installer no longer exists because installation is so easy now. I have removed the mentioning of it in https://github.com/Originate/exosphere/commit/47b93d58170e5e1f3c8a0feb2ffbd18395f88467.
