### ISSUE TITLE
new "exo create" command

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere#311]
> When starting to work on a new Exosphere application
I want to be able to generate the application programmatically
So that I don't have to read documentation to determine how to set up the application minutiae.

- running "exo create" generates an application scaffold
- the tool asks the user about information it needs
- the tool uses Boilr under the hood
- the command is written in Go

**Comment by cheahuychou** [comment]
closed in: https://github.com/Originate/exosphere/commit/7039459b3cfb7867a39f9ed4292b14368a754114
