### ISSUE TITLE
new "exo run" command

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere#313]
> When working on an Exosphere application
I want to be able to boot it up on my machine
So that I can see the code I am working on in action.

#### Rules
- running "exo run" boots up the application
- before running, the code base is prepared to run, for example by installing dependencies of the services
- when the application is running, it displays "application is online" in the terminal
- the terminal shows the output of the different services, each line preceded by the service name
- Ctrl-C stops all services

#### Notes
- in the old implementation, the setup steps are defined in `service.yml` and in the Dockerfile for the service. In the new implementation, they should be only defined in the Dockerfile.
- running "exo setup" is no longer a requirement for running this command. It should do the necessary setup on its own

```cucumber
Scenario: running a freshly cloned application
  Given I am in the root directory of a freshly cloned Exosphere application
  When running "exo run"
  And waiting it displays "application is running"
  Then my application is running

**Comment by cheahuychou** [comment]
closed in #364
