### ISSUE TITLE
boot up dependencies separately from services

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere#315]
> When using dependencies that take a while to boot up
I want "exo run" to wait before it boots up services that depend on them
So that my services find fully running dependencies when they boot up and don't have to implement complicated wait or retry logic to connect to their dependencies.

- "exo run" first boots up all dependencies, and only when they all run then all the services
- the dependencies include application and service dependencies
- after the dependencies are up, it prints "dependencies are online"
- after the services are up, it prints "services are online"

**Comment by cheahuychou** [comment]
closed in: https://github.com/Originate/exosphere/commit/114650a41c58c210805ee4f2d9b3ae621ebff121
