### ISSUE TITLE
remote Exocom service templates

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere#317]
> When developing Exocom applications
I want to be able to use the official Exocom templates
So that I can scaffold my services based on those templates.

#### Rules
- templates are in a dedicated repo on Github, ideally as part of https://github.com/originate/exocom
- templates can be referenced as normal [remote Boilr templates](#318)

#### Templates 
- [ ] Exorelay-Go 
- [ ] Exoservice-Go
- [ ] Exorelay-JS
- [ ] Exoservice-JS

**Comment by kevgo** [comment]
blocking on #318

**Comment by cheahuychou** [comment]
Where should these templates go? `templates` folder in https://github.com/originate/exocom?

**Comment by kevgo** [comment]
If that works with Boilr, then yes. If Boilr insists on seeing templates in a dedicated repo, then we have to do that.

**Comment by charlierudolph** [comment]
Unblocking since #318 is closed

**Comment by charlierudolph** [comment]
Closing as exoservice templates have already been extracted. We never had exorelay templates
