### ISSUE TITLE
remote Boilr templates

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere#318]
> When developing a fleet of similar applications
I want to be able to use service templates from a remote location
So that I don't have to copy-and-paste templates into all my application code bases.

- if application.yml contains an entry "templates" that points to a [Boilr template URL](https://github.com/tmrts/boilr#download-a-template), Exosphere imports those templates into Boilr
- running "exo update-templates" re-imports the templates
- "exo create" has to ask for the template URL, if none is given it omits the entry in application.yml

**Comment by hugoesthere** [comment]
What do you think about calling this command `exo fetch-templates`?

**Comment by kevgo** [comment]
+1 on `git fetch-templates`!

**Comment by cheahuychou** [comment]
resolved in: https://github.com/Originate/exosphere/commit/a46c971c38270c9c034f5cf754f39c5570d35f2d
