### ISSUE TITLE
index

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere#319]
## Exosphere roadmap

@hugobho
- milestone [new exo deploy](https://github.com/Originate/exosphere/milestone/1)

@cheahuychou
- milestone [new code generation](https://github.com/Originate/exosphere/milestone/2)
- milestone [new exo run](https://github.com/Originate/exosphere/milestone/3)

@mcharawi 
- Go port of Exocom

@charlierudolph 
- oversight, code reviews, coaching and training, pairing up, filling gaps

**Comment by charlierudolph** [comment]
@kevgo can this be updated or closed?
