### ISSUE TITLE
Come up with a way to do integration tests with say hundreds of services.

### ISSUE THREAD

**Issue by stefansavev-o** [Originate/exosphere#324]
This was another bottleneck I faced. 
How to make sure, after developing 4 different services they work well in production before integrating them in the front-end. For example, service d, consume a and c and c consumes a and b.
Unit tests in cucumber don't enforce that. For example the go exocom client used in tests is different than exocom that is deployed. Another issue not tested is compatibility between messages sent/receive between different services. A third issue is testing at scale, e.g. gigabyte size databases or hundreds of messages per second.

What I need here is a way to do the following:
- how to setup (preload) databases
- how to have "a driver" that sends lots of messages (e.g. a mock front-end)
- how to pass env. variables to multiple tests environments
- report success/failures measure latency/throughput under different scenarios

**Comment by kevgo** [comment]
Hey @stefansavev-o! All good points.
- [x] yes, we need end-to-end tests for applications to make sure all the services talk directly to each other. Here is the [ticket](https://github.com/Originate/exosphere-sdk/issues/12) for that.
- [x] yes, we need load tests by spinning up an app with hundreds of services ([ticket](https://github.com/Originate/exosphere-sdk/issues/241)), as well as for Exocom directly ([ticket](https://github.com/Originate/exosphere-sdk/issues/242)).
- [ ] can you please provide an example what ENV variables you want to pass around to the different environments? These should be defined in `application.yml`. @hugobho can you please work with @stefansavev-o today to work this part out?
- some of these tests will use services that emit a ton of messages, as you describe. These services will be remote-controlled by the test suite.

**Comment by hugoesthere** [comment]
The sdk currently doesn't have support for that - defining env vars in `application.yml`. What do you guys think is the best way to inject env vars? See: https://github.com/Originate/exosphere-sdk/issues/301

**Comment by stefansavev-o** [comment]
@hugobho I can't see the link.

**Comment by hugoesthere** [comment]
That seems to be on a private repo. @kevgo should we continue adding users to that repo or port that conversion over to this repo instead?

**Comment by kevgo** [comment]
@stefansavev-o I have added you to Team Exosphere. You should be able to see the private repo now.

**Comment by charlierudolph** [comment]
@kevgo @stefansavev-o anything left to do in this issue or can it be closed? It appears some things were extracted into other tickets

**Comment by kevgo** [comment]
Good to close from my end, but @stefansavev-o should chime in as well here.

**Comment by stefansavev-o** [comment]
Thank you!
