### ISSUE TITLE
exo-deploy: enable encryption by default on RDS instances

### ISSUE THREAD

**Issue by Bowbaq** [Originate/exosphere#341]
RDS supports encryption at rest, but it is [not enabled by default](https://www.terraform.io/docs/providers/aws/r/db_instance.html#storage_encrypted) by terraform. 

- [ ] Update the `rds` module so that storage is encrypted by default. 
- [ ] Investigate using our own KMS key (AWS will supply a default one otherwise). Is this useful?

**Comment by charlierudolph** [comment]
Moved to epic in exosphere-sdk
