### ISSUE TITLE
exo-deploy: enable ECS task autoscaling

### ISSUE THREAD

**Issue by Bowbaq** [Originate/exosphere#342]
Both ECS and terraform support enabling [autoscaling](https://www.terraform.io/docs/providers/aws/r/appautoscaling_policy.html) of ECS tasks.

- [ ] Update the task module to setup autoscaling policies. This should provide reasonable defaults (see the `ecs-cluster` module for an example) but be overridable by the end user.

**Comment by charlierudolph** [comment]
Moved to epic in exosphere-sdk
