### ISSUE TITLE
exo-deploy: allow creating an RDS instance from a snapshot

### ISSUE THREAD

**Issue by Bowbaq** [Originate/exosphere#344]
RDS instances can be created from a snapshot. This is useful in several cases, namely renaming a database instance (which causes a new instance to be created). The `rds` module currently does not support this.

- [ ] Add an optional [`snapshot_identifier`](https://www.terraform.io/docs/providers/aws/r/db_instance.html#snapshot_identifier) parameter

**Comment by charlierudolph** [comment]
Moved to epic in exosphere-sdk
