### ISSUE TITLE
go: update package names

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#374]
Update package names to be have no dash / underscore.

See https://blog.golang.org/package-names

Some possible updates:
* test_helpers -> test/helpers, test/featurectx
* app_*, service_config_helpers, service_restarter -> application
* docker_* -> docker
* os_helpers (move into util)
* template_helpers -> template
* terraform_file_helpers -> terraform

Ideally do one package consolidation / update at a time to keep reviews easy and get it merged quickly to prevent conflicts.

**Comment by kevgo** [comment]
👍 have to refactor the helpers a bit in my opinion as well. I think we have to understand better how to do those idiomatically in Go.
