### ISSUE TITLE
templates: extract to dedicated repos

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#376]
Each of the boilr templates should be extracted into their own repo
* exoservice-es6-mongodb
* htmlserver-express-es6

@kevgo any other templates you think are worth building boilr templates for? 
I think `exoservice-go` / `exoservice-es6` might be good ones. The livescript versions probably aren't important

Also what do you think these should live? Should we keep them under Originate with the a prefix like `exosphere-template`? Or could create an exosphere or even exopshere-template organization which we can have them live under.

**Comment by kevgo** [comment]
Yes let's throw away the livescript templates, I have to admit defeat in the name of the entire livescript ecosystem  😢 

For now, let's put them under Originate as `exoservice-go` and `exoservice-js`.

**Comment by charlierudolph** [comment]
Any idea for the naming of `htmlserver-express-es6` to make it more apparent it is an exosphere template or do you think that is fine as is?

**Comment by kevgo** [comment]
`exosphere-htmlserver-express`? Since ES6 is the standard, I don't think we have to call it out explicitly.

**Comment by charlierudolph** [comment]
Sounds good

**Comment by charlierudolph** [comment]
Templates:

https://github.com/Originate/exoservice-go
https://github.com/Originate/exoservice-js
https://github.com/Originate/exoservice-js-mongodb
https://github.com/Originate/exosphere-htmlserver-express
