### ISSUE TITLE
build template tester

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#395]
Build a tool that can be used by people creating templates to test their templates.

Tool will:
* create an empty application
* add the current template with supplied answers to boilr prompts
* run the tests

**Comment by charlierudolph** [comment]
@kevgo @hugobho @mcharawi thoughts on this being a part of exo? something like `exo template test` which you would run in the directory of a template? I think thats the easiest way to go about this.

**Comment by kevgo** [comment]
If a user would run this on their own templates, then yes, it can be part of Exosphere. If not, then let's make it its own tools.
