### ISSUE TITLE
exo-lint

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#406]
Should this be extracted to its own repo or what is the plan for this? @kevgo you had said this is exocom specific.

Implementation available [here](https://github.com/Originate/exosphere/tree/v0.22.1/exo-lint)

**Comment by kevgo** [comment]
Yes, let's extract this into its own stand-alone tool. It will live in the Exocom repo.

**Comment by charlierudolph** [comment]
Should we leave it as written in JS for now? I don't see any reason to rewrite it at the moment. Also should it be renamed to exocom-lint?

**Comment by kevgo** [comment]
Great ideas!

**Comment by charlierudolph** [comment]
Moved to https://github.com/Originate/exocom/issues/207
