### ISSUE TITLE
security adapter: exorelay / exoservice

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere#455]
Should retain the `isSecurity` flag when responding to messages (similar to sessionId)

**Comment by charlierudolph** [comment]
* exorelay
  * Allow `isSecurity` to be set when sending a message
* exoservice
  * The reply handler passed to the function will set the `isSecurity` flag on the response as the same value of the incoming message

**Comment by mcharawi** [comment]
closed by https://github.com/Originate/exocom/pull/240
