### ISSUE TITLE
security adapter: exosecurity

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere#456]
Wraps exorelay to provide an interface where the user defines a single function which takes in a message to authorize and a function to make a data request. The function returns a boolean (possibly in an asynchronous manner).

The function to make a data request puts the data request as the payload in a `security request` message retaining the activityId.

On the arrival of a `security response` message with the proper `activityId` it passes the message in the payload to wherever was waiting for that response. 

See #457 for an example of the what the outgoing and incoming requests should look like

**Comment by charlierudolph** [comment]
See https://github.com/Originate/exocom/compare/exosecurity?expand=1 for an initial feature. We are basically going to be creating the inverse features as what was written for exocom. After that feature is implemented, we can add a feature for the ability to make a data request as part of authorization.

I envision the user would use something like
```go
exosecurity.Bootstrap(func(message *structs.Message, requestData exosecurity.DataRequester) bool {
  // custom logic
})
```

Checkout exoservice for a similar test setup and

**Comment by mcharawi** [comment]
Closed by https://github.com/Originate/exocom/pull/243 and https://github.com/Originate/exocom/pull/242
