### ISSUE TITLE
exo remove

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#496]
I think this would be very nice to have. When run it would prompt the user to select what service to remove. Currently this is done manually in two steps: delete the folder and update `application.yml`.

@kevgo @hugobho @mcharawi thoughts? I've done this manually a few times and think it would be nice to have.

**Comment by mcharawi** [comment]
Well if we have `exo add` then `exo remove` seems like the logical next step.

**Comment by kevgo** [comment]
As long as people use this. I can see myself doing this manually each time. It just happens rarely enough to forget that such a command exists.

**Comment by charlierudolph** [comment]
Closing as easy enough to do manually
