### ISSUE TITLE
Add concept of "private" service

### ISSUE THREAD

**Issue by hugoesthere** [Originate/exosphere#500]
In production we need public, private and worker services. These services are defined as follows:

- Public: has an external facing ALB that lives in the public subnet, plus an internal ALB in the private subnet
- Private: has an internal facing ALB in the private subnet
- Worker: has no load balancers

All services themselves live in the private subnet. Currently we have public and worker services (though we call them private). This ticket is to add the private service and rename what we currently call private to worker. There is no affect on the dev environment.

**Comment by kevgo** [comment]
Are workers not auto-scaling?

**Comment by hugoesthere** [comment]
ECS will spin up more instances of these services if any of them get sweaty (including the worker services). In addition to distributing traffic, the load balancers also act as a central address that other services can hit. That's a feature that the public/private services need but not the workers.
