### ISSUE TITLE
Service restart

### ISSUE THREAD

**Issue by hugoesthere** [Originate/exosphere#518]
Our current implementation of service watching/restarting using `fsevents` isn't support on macOS. Write a version that works. See feature files for details.

**Comment by alexdavid** [comment]
I think we should use volume mounting in docker over watching the host filesystem for changes and restarting the service. This allows us to use tech-stack-specific solutions to recompiling/restarting which could be much faster than rebuilding the docker container. This also removes the need for exosphere to watch the filesystem for changes.

**Comment by hugoesthere** [comment]
Resolved with https://github.com/Originate/exosphere/commit/9d8c48537db0c36e83516a5eeec7cc9a4127f516
