### ISSUE TITLE
exo deploy: check aws / terraform are installed

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#525]
Display an error message listing these as requirements and asking them to be installed. If there are minimum version requirements, list them as well.

**Comment by kevgo** [comment]
Don't we run Terraform inside Docker?

**Comment by charlierudolph** [comment]
Currently not

**Comment by hugoesthere** [comment]
@kevgo do we want to move to running Terraform and AWS inside Docker?

**Comment by kevgo** [comment]
If that's possible, it would be nice if I don't have to download Terraform and AWS on my machine, but only Exosphere.

**Comment by charlierudolph** [comment]
Closing as we don't need AWS to be installed and we are now running terraform in docker
