### ISSUE TITLE
exo deploy: verify secrets include terraform requirements

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#526]
* account_id
* aws_profile
* region
* key_name
* ssl_certificate_arn

**Comment by charlierudolph** [comment]
After #538 and #529, the only one we should need to verify is `key_name`

**Comment by charlierudolph** [comment]
Possibly unneeded if we can leave the key name blank

**Comment by hugoesthere** [comment]
`key_name` has a blank default value and Terraform has no problem with this.
