### ISSUE TITLE
exo deploy: validate production sections of app/service.yml 

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#528]
For example setting the cpu and memory

**Comment by kevgo** [comment]
FYI @alexdavid has the idea to extract this part into Terraform files.

**Comment by charlierudolph** [comment]
+ whatever we add to the app yaml in other tickets

**Comment by hugoesthere** [comment]
Closed in https://github.com/Originate/exosphere/commit/1f3f1eb5a6d4974ad44fae4b709a2e55f8a9ffaf
