### ISSUE TITLE
exo deploy: selectively push dependency images to ECR

### ISSUE THREAD

**Issue by hugoesthere** [Originate/exosphere#535]
Currently, we deploy all images listed in `application/docker-compose.yml` to ECR when running `exo-deploy`. This is unnecessary for dependencies such as databases for which we have an alternative solution for in production. Furthermore, when we switch to deploying different versions of dependencies in deployment (as discussed here: https://github.com/Originate/exosphere/issues/508) , we can no longer just read `application/docker-compose.yml` and push those images.

Perhaps now is even the time to consider breaking up `docker-compose.yml` into a `service-docker-compose.yml` and `dependencies-docker-compose.yml`.

**Comment by charlierudolph** [comment]
@hugobho was this resolved in one of your recent PRs?

**Comment by hugoesthere** [comment]
Yes, resolved in https://github.com/Originate/exosphere/commit/e2fd22d817731b0dddbfef1bc19b0eabf4b0e1b5
