### ISSUE TITLE
Service.yml port specification

### ISSUE THREAD

**Issue by alexdavid** [Originate/exosphere#543]
Right now in `service.yml` there are two sections where you specify what ports your application listens on:

```yaml
docker:
  ports:
    - 3000:3000

production:
  public-port: 3000
```

I don't think this makes much sense. If one of the design goals of this `service.yml` file is to document high level constructs that we use to generate docker-compose and terraform files we really should not expect users to manually manage this.

Also as a user I don't want to have to think what free ports I have available, if I have hundreds of services I have to go through each one to make sure the host port is unique for each one.

Instead I suggest one top-level configuration option: `application-ports` which document ports that should be opened in development and production mode.

In development mode we find free host ports for each port listed and create the mapping for docker, and for production we create an ALB for each port listed.

The final piece is that applications should stop printing out `service online at port ____` because that is useless information to the user because that's a container port not a host port. Instead exo run should print out the port each application is using when it sees the online text which instead of `online at port` should just be something like `service ready`.

**Comment by alexdavid** [comment]
Also we should move health check out of production as well. We could use that instead of regex searching stdout to test when a service is online.

Changes like this will make bugs more likely to be tracked down before pushing to prod. (What if the healtcheck endpoint is broken?)

This obviously doesn't work for non-http services but we need to document services that aren't http for production anyway

**Comment by alexdavid** [comment]
This obviously doesn't work for non-http services but we need to document services that aren't http for production anyway

**Comment by hugoesthere** [comment]
What is the purpose of `application-ports`? I thought the idea was that each service defines a `container-port` to expose if it needs one, we handle the port reservation during startup and then print that port out to them.

**Comment by alexdavid** [comment]
Yeah I think calling it `application-ports` or `service-ports` make more sense because the fact that we run it in a container is an implementation detail. The thing the user needs to define is what ports does the application/service listen on

**Comment by hugoesthere** [comment]
+1 to non-regex checks for services being online, but we'll need a solution for non-http services pretty quickly. The mongo services for one will need a health check equivalent. What does it look like then to check that each service is online? 

Should we could mandate that each service has a `health-check.js` or some binary we can execute that pings itself and checks that it's online?

**Comment by hugoesthere** [comment]
Checking for online status has been extracted into a separate ticket: https://github.com/Originate/exosphere/issues/544

**Comment by charlierudolph** [comment]
@alexdavid pulling in some comments I remember you making elsewhere and building on them

A service that exposes a single port can use the following shorthand
```yml
port: 80
```
which would cause other services to receive `MY_SERVICE_PORT`.

A service exposing multiple ports defines it as
```yml
ports:
  - number: 8000
    identifier: A
  - number: 8001
    identifier: B
```
The service gets port 8000 and 8001 mapped to free ports and other services receive `MY_SERVICE_PORT_A` and `MY_SERVICE_PORT_B`


The `MY_SERVICE` might also be configured by the user. This is if we are going with the env var approach but I really like the idea of the user saying what ports they expose and be able to give each an identifier if they expose multiple.

Not certain how exactly the public-port plays into this.

**Comment by charlierudolph** [comment]
Closing as the single port case is done. We can add support the multiple-port case as we need it
