### ISSUE TITLE
More robust online checks for services

### ISSUE THREAD

**Issue by hugoesthere** [Originate/exosphere#544]
Per @alexdavid's suggestions in https://github.com/Originate/exosphere/issues/543

> Also we should move health check out of production as well. We could use that instead of regex searching stdout to test when a service is online.
Changes like this will make bugs more likely to be tracked down before pushing to prod. (What if the healtcheck endpoint is broken?)
This obviously doesn't work for non-http services but we need to document services that aren't http for production anyway

We should implement more robust ways to check if a service is online, perhaps by requiring each service has an online-checker plugin. For instance http services could have file that runs a health check, some services could have binaries that do something similar, etc. As a last resort we should use online text.

**Comment by kevgo** [comment]
Does this mean putting an extra executable inside the Docker image, which Exosphere calls regularly, and which returns an error if the service isn't online?

**Comment by alexdavid** [comment]
Remove in favor of #698
