### ISSUE TITLE
exo deploy: deploy via CI

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#553]
Add a flag to exo deploy which does the following:

- does not prompt when the planning stage completes.
- If the planning stage causes changes to the `main.tf` file, exit with an error message telling the user to deploy manually in order to verify and commit the changes to `main.tf`
- Otherwise, apply the plan (this should be the more common case)

@kevgo @alexdavid @hugobho @mcharawi thoughts?

**Comment by kevgo** [comment]
Changes to the terraform file must be reviewed by an ops person, so I would say they always have to be committed by a developer. The CI server should simply deploy the code as-is to various environments. If it tests a commit on the `prod` branch, it deploys to production, if it tests a commit on the `qa` branch, it deploys to QA, etc. This branch mapping should probably be configurable in `application.yml`.

**Comment by hugoesthere** [comment]
Actually, after the initial deployment the only changes that should take place are in the service modules that are generated, which use the terraform modules that we've written and tested. These service modules shouldn't be changing too much infrastructure other than pointing a task definition to a new Docker image and maybe updating its route53 record. @chrizkim had the idea of having an ops person deploy the main infrastructure from their machine (the `aws` module), and then have CI deploy all the services.

Either way even if we're just bumping the version of the service without any other changes, we'll still be modifying the `.tf` files so I'm not sure how feasible it is to exit with an error every time `main.tf` is modified.

**Comment by charlierudolph** [comment]
Closing in favor of #620
