### ISSUE TITLE
move tmp directories to os tmp dir

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#575]
* Move the tmp directories we create during `exo run` and `exo test` to the operating system tempdir.
* Add a `--local-tmp` option to retain the old behavior so we have an easy way to look at the docker compose files when we want to debug.

**Comment by charlierudolph** [comment]
@hugobho I think this might not work because `exo clean` needs to use those docker compose files. Could we update `exo clean` to generate the docker compose files and then run `docker-compose down` in each?

**Comment by hugoesthere** [comment]
Yeah, looks like that's what we'll have to do.

**Comment by charlierudolph** [comment]
Closing this in favor of #697
