### ISSUE TITLE
update js templates to auto restart on changes

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#577]
* via nodemon or supervisor

**Comment by kevgo** [comment]
What I don't like about this approach is that it makes something that should be provided by the framework a problem of the developer. Now each one of my services needs some custom monitor or supervisor running inside Docker, which makes the services more complicated, error-prone, and confusing. 

Given that we already have code to restart individual Docker images on file change, why not introduce this config setting called `restart` into `service.yml` with these options:
- `none` - don't restart this service (it restarts itself)
- `change` - Exosphere restarts the Docker image when it detects a filesystem change event

**Comment by charlierudolph** [comment]
> Given that we already have code to restart individual Docker images on file change

That was removed in favor of mounting the directory and having the developer use their language specific way which is orders of magnitude faster

**Comment by kevgo** [comment]
Is the conclusion that restarting the Docker image is always too slow, and we are better off with a nodemon based approach?

**Comment by charlierudolph** [comment]
@kevgo yes. Going to close this as for now as we can improve the templates the next time we use them
