### ISSUE TITLE
Service memory management

### ISSUE THREAD

**Issue by hugoesthere** [Originate/exosphere#611]
Determine a solution to properly allocating container memory in production so ECS doesn't have trouble scheduling tasks, and ASG can actually spin up new instances if needed.

@alexdavid's proposed solution: Let the user decide the hard/soft limits for each service. We determine the instance type needed to support that and adjust the cluster size to be big enough for the base case.

Open to other solutions. @chrizkim

**Comment by charlierudolph** [comment]
Closing as this will be addressed when we move to new terraform modules that are used on other project
