### ISSUE TITLE
terraform: prevent unnecessary changes

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#619]
Couple unnecessary changes to a projects `main/terraform.tf` that I saw.

* Currently the AWS profile appears in the terraform file. Is this required? This will change if you have two different people deploying who have named that specific AWS account differently. For @hugobho had deployed using an aws profile: `edx` and mine is named `default`
* In the deploy, a couple services switched order in the terraform file. Can we alphabetize the services before creating terraform modules in order to make this more consistent?

Related to #613

@hugobho @alexdavid thoughts?

**Comment by hugoesthere** [comment]
To the first bullet point, I had noticed this too. I think we can just make it a variable - we know have the value in the go code anyways. As for the second bullet point, I suppose we should just be able to do that in the go code as well? There's a map of services that we loop through and append their modules. We should do the same with dependencies.

**Comment by charlierudolph** [comment]
Closing in favor of #624 and #625
