### ISSUE TITLE
exo deploy: new option

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#620]
New option for exo deploy that can be used in CI. 

* `--update-service-images`: used on ci. Instead of prompting for confirmation, if the main.tf file is unchanged, deploys the updates (the new services). Otherwise exits with an helpful error message like `"terraform/main.tf" has changed. Please deploy manually to review these changes.` Then use the `-target` flag to only update the service instances

@hugobho @alexdavid @chrizkim thoughts? Is there anything else we would need to look for?

Blocking Tickets
* [x] #623 
* [x] #624
* [x] #625

**Comment by hugoesthere** [comment]
That `main.tf` file would still reflect the new version number in the `docker-image` field of a service module. Unless you were thinking about updating that field before pushing to ci. @chrizkim also mentioned using the `terraform -target` flag to target specific modules, we could probably use that here as well.

**Comment by charlierudolph** [comment]
Hmm. Is there any way we can move the docker version numbers of out the terraform file or tell that this the only thing that changed?

**Comment by hugoesthere** [comment]
We can do what @alexdavid suggested and have them be vars instead of hardcoded

**Comment by hugoesthere** [comment]
Perhaps we shouldn't use the `-target` flag. From the terraform docs: 
> It is not recommended to use -target for routine operations, since this can lead to undetected configuration drift and confusion about how the true state of resources relates to configuration. Instead of using -target as a means to operate on isolated portions of very large configurations, prefer instead to break large configurations into several smaller configurations that can each be independently applied.

Currently it is not needed anyways. It it becomes necessary in the future we can break the `.tf` files into `infrastructure.tf`, `dependencies.tf` and `services.tf`

**Comment by charlierudolph** [comment]
Sounds good
