### ISSUE TITLE
Use more unique s3 bucket names

### ISSUE THREAD

**Issue by hugoesthere** [Originate/exosphere#628]
Since s3 buckets are global if we simply name them `#{app-name}-terraform` and `#{app-name}-secrets` then we can't deploy to multiple accounts. We should figure out a more unique way of naming them.

**Comment by hugoesthere** [comment]
@charlierudolph @alexdavid any suggestions for what we should name them? Some combination of app name and account id?

**Comment by charlierudolph** [comment]
Thoughts on also including the region as I thought we could do multiple environments by deploying to another region?

```
#{account-id}-#{region}-#{app-name}-terraform
```

**Comment by hugoesthere** [comment]
I think Chris had shot down the idea of deploying to multiple envs by deploying to another region

**Comment by charlierudolph** [comment]
Auhh okay. Then `#{account-id}-#{app-name}-terraform` seems fine to me
