### ISSUE TITLE
plan refactors

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#649]
application / docker

cmd - is only calling out to high level API methods, 
parse CLI flags / reading env variables

new exo test is a good example

GetContext could live in cmd

-------------------------

exo run 

docker-compose-runner

spin up dependencies
spin up services

-------------------

pushToECR() method 
returns version

run() method

passing in docker options

**Comment by hugoesthere** [comment]
What about the consolidation of `serviceRole` and `serviceName`? Also related is finalizing what we decide to call the dir name of a service and the key it's represented by in app.yaml

**Comment by charlierudolph** [comment]
Closing as we already have some of this done and other issues for more cleanup
