### ISSUE TITLE
example apps: update dockerfiles

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#657]
We have a few example-apps that pull a dockerfile from `FROM nodesource/node`. Update this to `FROM node` as it has yarn preinstalled (we have this working on EDX).

**Comment by hugoesthere** [comment]
<img width="1674" alt="screen shot 2017-10-10 at 10 06 23 am" src="https://user-images.githubusercontent.com/7258240/31410510-aace9154-adc3-11e7-864d-f04f3cd29e21.png">

Been running into this error when trying to update `example-apps/tests-cucumber`. If anyone has a way of working around that, I've pushed my changes to `hh-update-dockerfiles`.
