### ISSUE TITLE
exo deploy: push image progress

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#670]
when pushing images to ECR do we get any progress indications that we could display to the user?
This has been the slowest step and I would like to give % complete updates. (especially because I have a slow connection in utah)

**Comment by hugoesthere** [comment]
This is the output we get:
<img width="1391" alt="screen shot 2017-11-01 at 10 01 12 am" src="https://user-images.githubusercontent.com/7258240/32286993-914a57e2-beec-11e7-9484-41765f255583.png">

It's possible we could print the progress by calculating the percentage of `current` to `total`? The image push method also returns a `ReadCloser`, is it possible to pipe the output from that directly to stdout?

**Comment by charlierudolph** [comment]
Hmm that looks a bit complicated. Maybe better than a percentage was can at least  we just print messages like:
```
Layer already exists: <id>
Pushing layer: <id>
```
Where pushing layer, only get printed once per layer. That way we are giving some step progess

**Comment by hugoesthere** [comment]
The problem is we read the output stream until EOF or error, so we can only parse the output once the process has finished anyways: https://github.com/Originate/exosphere/blob/master/src/docker/tools/index.go#L145 

Is there another method we can use that just reads data as it's piped over the stream?

**Comment by charlierudolph** [comment]
Use `bufio.Scanner` to read one line at a time. See https://golang.org/pkg/bufio/#Scanner
