### ISSUE TITLE
time metrics

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#680]
In order to make it easier to address bottlenecks and learn what is slow, I'd like us to add in a bunch of timing information. On EDX, I tried to address "testing" when I think the real slow downs were building and spinning up dependencies.  

For `exo test`  (after each individual and a total metric at the end)
* building 
* spinning up dependencies
* testing

For `exo run`
* building
* spinning up deps
* spinning up services

For `exo deploy`
* building
* pushing
* planning
* applying

**Comment by kevgo** [comment]
Maybe add a logger that includes the time delay to the previous message, like https://www.npmjs.com/package/debug. Plus a `loglevel` option to print more logging messages if one wants to debug timing. Ideally, there is a logging library out there that gives us all of this for free.
