### ISSUE TITLE
Service endpoint environment variables

### ISSUE THREAD

**Issue by alexdavid** [Originate/exosphere#685]
I think for web services we should expose env variables `SERVICE_[service-name]_ORIGIN` and `SERVICE_[service-name]_EXTERNAL_ORIGIN`

and worker services should expose `SERVICE_[service-name]_HOST`

Origin would include protocol (http/https) and external is for access to the service not within the network (port forwarding locally in docker & fqdn in production)

For example, suppose we have a web service named "frontend" and a worker service named "ftp-api":
* Frontend service runs on container port `8080` in development mode and `80` in production mode. Exosphere locally binds host port `3000` for this service
* ftp-api service runs on container port `2121` in development and `21` in production mode. Exosphere locally binds host port `3001` for this service and ECS binds host port `65000` for this service

We would inject the following variables into each service:
### `SERVICE_FRONTEND_ORIGIN`
<table>
<tr><th>Local development value</th><td>http://frontend:8080</td></tr>
<tr><th>Local production value</th><td>http://frontend:80</td></tr>
<tr><th>AWS production value</th><td>http://frontend.local</td></tr>
</table>
Useful if one service needs to make an http call to another service. Routes to the ALB in production we will need to enable HTTP alb exposed to only the cluster.

### `SERVICE_FRONTEND_EXTERNAL_ORIGIN`
<table>
<tr><th>Local development value</th><td>http://localhost:3000</td></tr>
<tr><th>Local production value</th><td>http://localhost:3000</td></tr>
<tr><th>AWS production value</th><td>https://frontend.myapp.com</td></tr>
</table>
Useful for services that need to tell programs running outside the network (frontend javascript) where to access other publicly exposed services. Note that we automatically route to the https origin in production.

### `SERVICE_FTP_API_HOST`
<table>
<tr><th>Local development value</th><td>ftp-api:2121</td></tr>
<tr><th>Local production value</th><td>ftp-api:21</td></tr>
<tr><th>AWS production value</th><td>ftp-api.local:65000</td></tr>
</table>
Useful for services that need to communicate directly with non-web services. note that for worker services we need to have them query the ec2metadata api and update their route53 record to match its scheduled EC2 box.

Thoughts @chrizkim @charlierudolph @kevgo @hugobho ?

**Comment by hugoesthere** [comment]
Looks good to me 👍

**Comment by kevgo** [comment]
I like it. Just to make sure I understand: Does this mean that in dev mode, inside the `frontend` docker image the variable `SERVICE_FRONTEND_ORIGIN` will be `http://frontend:8080`, while in other Docker images (for example inside the `ftp` docker image, it will have the value `http://localhost:3000`?

Does this mean that `SERVICE_FRONTEND_ORIGIN` and `SERVICE_FRONTEND_EXTERNAL_ORIGIN` will have the same value in all Docker images that are not `frontend`? If that is the case, I propose to not even expose `SERVICE_FRONTEND_ORIGIN` in non-frontend Docker images. And maybe rename the variables to `SERVICE_FRONTEND_INTERNAL_ORIGIN` for the internal port and `SERVICE_FRONTEND_ORIGIN` for the external port.

**Comment by alexdavid** [comment]
No `SERVICE_FRONTEND_ORIGIN` will be `http://frontend:8080` for all services when running locally. This should resolve to the frontend service. `localhost` within a container would be that container.

**Comment by alexdavid** [comment]
Services will use `SERVICE_FRONTEND_ORIGIN` when they need to directly send an http request to the frontend service, and use `SERVICE_FRONTEND_EXTERNAL_ORIGIN` if they send the URL outside their network to be requested (for example sending the url to a browser to make an external request)

**Comment by kevgo** [comment]
Ah, cool. That's even better!

**Comment by charlierudolph** [comment]
Closing for now as the `INTERNAL_ORIGIN` and `EXTERNAL_ORIGIN` are done. I'll create a new ticket for private services that communicate via non-http.
