### ISSUE TITLE
commit docker compose files

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#697]
Put docker compose files in a dedicated folder in the repo. Possibly something like the following:

* docker-compose
  * [ ] run_development.yml
  * [ ] run_production.yml
  * [ ] test.yml (when running tests, pick the service that needs to be run)
* ostmpdir
  * [ ] docker-compose.yml (for deployment)

Each are generated on demand, if needed

* [x] Switch `exo clean` to clean from these files.

@alexdavid @hugobho please review

**Comment by charlierudolph** [comment]
Deployment technically also uses a compose file. Do we think that is worth committing? That could go in a os tempdir if not

**Comment by hugoesthere** [comment]
I don't think so, it's really only building images. What if we had `exo-deploy` read from `run_production.yml`? That would make the most sense to me, that way what you test with `exo run --production` is what's pushed to ECR

**Comment by charlierudolph** [comment]
`run_production.yml` may include development dependencies though

**Comment by charlierudolph** [comment]
Lets do this one compose file at a time. The `run` compose files should be pretty easy. The test compose file will be a bit of a refactor as we create one for the entire application. Thus probably do this in two PRs
