### ISSUE TITLE
stop spinning up dependencies first

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#698]
Instead of using docker-compose to spin up dependencies and then services, remove this feature and spin up all at once. This is similar to what is done in production so its important that services can handle coming up before their dependencies.

This may remove the need for "online text", unless we want to keep telling the user when everything has booted up. I don't think thats very important though.

@alexdavid @hugobho please review

**Comment by hugoesthere** [comment]
👍 I agree, we should get rid of the online text stuff
