### ISSUE TITLE
Rename BuildDockerCompose in Initializer

### ISSUE THREAD

**Issue by hugoesthere** [Originate/exosphere#700]
exo-deploy builds the docker-compose.yml file, but never runs `docker-compose build` or `pull` before pushing, perhaps due to confusing naming (see: https://github.com/Originate/exosphere/blob/master/src/application/deployer/index.go#L36-L40). Will work on this ticket after refactor PRs are merged

**Comment by hugoesthere** [comment]
Nevermind, it seems that we do build the images down the line but exosphere wasn't picking up my local changes because I hadn't committed them yet (so a new SHA wasn't being generated). Regardless, I would still be open to renaming `BuildDockerCompose` to `CreateDockerComposeFile`

**Comment by charlierudolph** [comment]
Please update the title of the this PR to reflect that it is only a rename.

**Comment by charlierudolph** [comment]
This may be out of date now that #696 was merged which removed the initializer
