### ISSUE TITLE
exo deploy --profile does not work

### ISSUE THREAD

**Issue by alexdavid** [Originate/exosphere#702]
Running exo deploy with a profile fails with the following error: 

```
Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now reconfigure for this backend. If you didn't
intend to reconfigure your backend please undo any changes to the "backend"
section in your Terraform configuration.


Error loading previously configured backend:
Error configuring the backend "s3": No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider

Please update the configuration in your Terraform files to fix this error.
If you'd like to update the configuration interactively without storing
the values in your configuration, run "terraform init".
: exit status 1
```

**Comment by hugoesthere** [comment]
I can't seem to reproduce this on my machine. Can you print `deployConfig.AwsConfig.Profile` in both these functions and show me the output:
https://github.com/Originate/exosphere/blob/master/src/terraform/commands.go#L11
https://github.com/Originate/exosphere/blob/master/src/terraform/command_helpers.go#L14

**Comment by alexdavid** [comment]
Removing the `.terraform` directory and `terraform.backup.tfstate` seems to have resolved the issue. I guess terraform caches these values and changing them after the fact breaks things. This is probably a terraform bug.
