### ISSUE TITLE
new command: exo generate

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#749]
Generate all the docker-compose and terraform files. 

`run`, `test` and `deploy` all do this at the beginning of there command.

Pair with `exo needs-generate`which checks if the docker-compose and terraform files are up to date.

@hugobho what do you think? @alexdavid and i were discussing this.

**Comment by hugoesthere** [comment]
Then anytime you run a command the docker-compose/terraform files are updated - I'm not opposed.

Not sure about `exo needs-generate`, if it's going to check if those files are out-of-date, it might as well update them. In which case `exo needs-generate` just looks a lot like what `exo setup` used to.

**Comment by charlierudolph** [comment]
`exo needs-generate` is for CI to ensure the generated files are up to date.

**Comment by hugoesthere** [comment]
Should we name it `exo ci-check` or something then?

**Comment by charlierudolph** [comment]
We could add `test-ci` which checks the generated files are up to date and runs the tests.

**Comment by hugoesthere** [comment]
So we're going to have `run`, `test`, `deploy`, and `clean` always generate all the docker-compose files for each environment before running their respective processes, and `exo generate` will do the same. Then `exo test-ci` will be run on CI to check that generated files are up to date/run tests. Does that sound right?

**Comment by charlierudolph** [comment]
Lets actually do `exo test --ci` to add the check on the generated files. Lets split this into multiple PRs as well. The first on just one command (since that will do most of the setup). The second for the othe three commands. And the third for the update to check generated files.

**Comment by hugoesthere** [comment]
Do you mean do `exo generate` first and then update `run`, `test`, `deploy` and `clean` to use them?

**Comment by charlierudolph** [comment]
Not what I meant as I forgot about `exo generate` but that sounds better.

**Comment by hugoesthere** [comment]
I didn't think `exo generate` had much use other than the one edge case where a user makes a change, doesn't run one of the 4 run/test/etc commands, and tests fail via `exo test --ci` and they have to use it. But other than that I wasn't much of a proponent for `exo generate` either.

**Comment by charlierudolph** [comment]
Correct its for fixing the changes and if someone want to generate the files and inspect them (most likely terraform) without needing to run / deploy anything.

**Comment by hugoesthere** [comment]
Logging steps to track progress:
- [ ] implement `exo generate`
- [ ] point `run`, `test`, and `clean` to use `exo generate`

**Comment by alexdavid** [comment]
I don't like calling this `test --ci` or `test-ci`. The fact that we may run this on CI is just a usecase of the command and shouldn't be reflected in the command name.

Perhaps `exo genereate --check`?
