### ISSUE TITLE
dependency hostname environment variables

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#757]
Make EXOCOM_HOST, NATS_HOST, etc be auto injected during the compose build phase and thus not need to be defined in the dependency.

**Comment by hugoesthere** [comment]
How do we plan on implementing this? Should we make dependencies another service endpoint? And how does the container name refactor affect this? The container name used to be the dependency endpoint.

**Comment by charlierudolph** [comment]
Hmm, I don't know that we need this story. Maybe a better goal is to remove all local dependencies and only be left with the generic dependency. Please hold on this for now

**Comment by charlierudolph** [comment]
done in 6f4feacda8e8b14971064b1b237bb71f48c28887
