### ISSUE TITLE
display full commands 

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#779]
When outputting what commands are run: also output the directory its run in and the env vars provided.

@alexdavid @hugobho what do you think?

I expect this to get a bit crazy for the terraform command as the env vars are huge but this is trying to be transparent so a user that knows docker compose can do some manual tinkering if we don't support something yet.

One of the devs on EDX brought this up as he wanted to run docker manually in order to expose a second port since we don't support that yet

**Comment by alexdavid** [comment]
I like this. It makes exosphere feel less magical and helps expose the underlying technologies
