### ISSUE TITLE
switch to terraform 0.11.0

### ISSUE THREAD

**Issue by hugoesthere** [Originate/exosphere#787]
Use default confirmation prompt in `terraform apply` and get rid of `terraform plan`.

Also lock in required version in `terraform/templates/aws.tf` to 0.11.0 so we don't run into problems with people deploying with difference terraform versions.

```
terraform {
  required_version = "= 0.11.0"
...
```

**Comment by charlierudolph** [comment]
We do want to at least lockdown the terraform version to a range in order to avoid breaking changes. I don't know if we want to lock it to a specific version without making it configurable.

**Comment by hugoesthere** [comment]
This would be a breaking change anyways if we're getting the user to switch to `0.11.0`. The use case I'm thinking of is if we allow `>= 0.10.0 <= 0.10.8` (i'm not sure that' the correct syntax), then person A could have `0.10.1`, person B `0.10.2`. Person A deploys fine, but after person B deploys, person A won't be able to deploy until they switch to `>= 0.10.2`. And then you can imagine a whole team of developers just chasing each other up until they reach the upper limit of the range, at which point we might as well have just locked it down to the highest version
