### ISSUE TITLE
exo deploy: flag to use locally installed terraform

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#849]
By default, `exo deploy` runs terraform in a docker image. Add an option to use a locally installed version of terraform instead. 

~When using a locally installed version we need to validate terraform has the version we want.~

Maybe have the flag be `--local-terraform`

@alexdavid @hugobho please review

**Comment by hugoesthere** [comment]
I think when we define a terraform version in `main.tf` terraform won't run any commands unless the versions match up. In which case this flag is more of for running terraform outside of docker and less for using a different version. For supporting different version we need something more involved I think

**Comment by charlierudolph** [comment]
Cool. Yep the documentation confirms that: https://www.terraform.io/docs/configuration/terraform.html

Yeah the purpose is solely to run it outside of docker and not for running a different version. Just wanted to make sure we would get an error if the version was wrong.

**Comment by kevgo** [comment]
Do we really need this at this point? I’m not against it, but want to encourage you to focus on getting a basic working version done, release it,  and support the EDX team before adding other cool bells and whistles. Ideally there is only one way of using Terraform at this point, either inside or outside Docker.

**Comment by alexdavid** [comment]
The reason for this was to get this working on circleci docker executor again. I agree with @kevgo that this isn't very important now, but if circle makes machine executor a premium feature this will be more important.

I think this can be done later when we want to create the circleci dockerhub image to make CI set up a breeze.

**Comment by charlierudolph** [comment]
I think we were working fine with terraform in docker but we need to make sure we pass the aws env vars into docker. Otherwise I think we might as well revert 83ec0a1bfc48e1f7cc41e78b14ac403d8e9f50fe

**Comment by charlierudolph** [comment]
Closing as we reverted the change
