### ISSUE TITLE
terraform apply: command is too long

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#908]
Currently have a command that is way to long as the var flags are just massive. Was there a reason we decided against the var file? I think we had that originally and think that would be nicer for someone to look at. We could write it in the terraform dir and have that gitignored automatically.

**Comment by hugoesthere** [comment]
I can't remember exactly why we decided against a var file. I'm not opposed to using one again

**Comment by charlierudolph** [comment]
K. It appears we were initially using the secrets as a tf vars file and then switched it to json. I think this would be a really nice switch. Lets try it out.
