### ISSUE TITLE
extract production dependencies: move terraform modules

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#911]
I think we should move terraform modules from `terraform/aws/dependencies/*` into the `remote-dependencies-templates/*`

@alexdavid @hugobho thoughts?

**Comment by hugoesthere** [comment]
Yeah, they probably don't belong in `terraform/aws/dependencies/*`. Would now be the time to potentially consider moving these modules into their own repo? Or even just a single exosphere remote dependency terraform modules repo?

**Comment by charlierudolph** [comment]
Then we have to build in loading remote repos which I'd prefer not too yet. I think just moving them into the dependency would be sufficient.
