### ISSUE TITLE
application yml: default aws profile

### ISSUE THREAD

**Issue by charlierudolph** [Originate/exosphere#966]
Thoughts on updating the default aws profile used by `exo configure` / `exo deploy` to be the name of the project instead deferring to the aws default which is `default`. I think that will be the name of profile 99% of the time and makes it one less flag to supply as I have pretty much always  the `--profile` flag.

@alexdavid @hugobho thoughts?

**Comment by alexdavid** [comment]
I think this is too magical. I think we should mirror the aws tools here and be explicit about profile names

**Comment by charlierudolph** [comment]
Okay we can go without it for now. We'll see if we get any feedback about it down the road
